import { Router } from "express";
import {
  acceptInvitationController,
  addMemberController,
  addTeamMemberController,
  cancelInvitationController,
  checkOrganizationSlugController,
  createOrganizationController,
  createTeamController,
  deleteOrganizationController,
  getActiveMemberController,
  getActiveMemberRoleController,
  getInvitationController,
  getOrganizationController,
  inviteMemberController,
  leaveOrganizationController,
  listInvitationsController,
  listMembersController,
  listOrganizationTeamsController,
  listOrganizationsController,
  listTeamMembersController,
  listUserInvitationsController,
  listUserTeamsController,
  rejectInvitationController,
  removeMemberController,
  removeTeamController,
  removeTeamMemberController,
  setActiveOrganizationController,
  setActiveTeamController,
  updateMemberRoleController,
  updateOrganizationController,
  updateTeamController,
} from "../controllers/organization";
import { asyncHandler } from "../lib/async-handler";
import { validateBody, validateParams, validateQuery } from "../lib/validate";
import { requireAuth } from "../middleware/require-auth";
import { requireOrgRole, requirePermission } from "../middleware/require-role";
import {
  activeMemberQuerySchema,
  addMemberSchema,
  addTeamMemberSchema,
  checkOrganizationSlugSchema,
  createOrganizationSchema,
  createTeamSchema,
  invitationIdParamsSchema,
  inviteMemberSchema,
  leaveOrganizationSchema,
  listInvitationsQuerySchema,
  memberIdParamsSchema,
  organizationIdParamsSchema,
  organizationMemberParamsSchema,
  setActiveOrganizationSchema,
  setActiveTeamSchema,
  teamIdParamsSchema,
  teamMemberParamsSchema,
  updateMemberRoleSchema,
  updateOrganizationSchema,
  updateTeamSchema,
} from "../schemas/organization.schema";

export const organizationsRouter: import("express").Router = Router();

organizationsRouter.use(requireAuth);

organizationsRouter.get("/", asyncHandler(listOrganizationsController));
organizationsRouter.post(
  "/",
  validateBody(createOrganizationSchema),
  asyncHandler(createOrganizationController),
);
organizationsRouter.post(
  "/check-slug",
  validateBody(checkOrganizationSlugSchema),
  asyncHandler(checkOrganizationSlugController),
);
organizationsRouter.post(
  "/leave",
  validateBody(leaveOrganizationSchema),
  asyncHandler(leaveOrganizationController),
);
organizationsRouter.post(
  "/active",
  validateBody(setActiveOrganizationSchema),
  asyncHandler(setActiveOrganizationController),
);
organizationsRouter.get(
  "/active-member",
  validateQuery(activeMemberQuerySchema),
  asyncHandler(getActiveMemberController),
);
organizationsRouter.get(
  "/active-member-role",
  validateQuery(activeMemberQuerySchema),
  asyncHandler(getActiveMemberRoleController),
);

organizationsRouter.get(
  "/user-invitations",
  asyncHandler(listUserInvitationsController),
);
organizationsRouter.get(
  "/invitations",
  requirePermission("organization.invitation.manage"),
  validateQuery(listInvitationsQuerySchema),
  asyncHandler(listInvitationsController),
);
organizationsRouter.get(
  "/invitations/:invitationId",
  validateParams(invitationIdParamsSchema),
  asyncHandler(getInvitationController),
);
organizationsRouter.post(
  "/invitations/:invitationId/accept",
  validateParams(invitationIdParamsSchema),
  asyncHandler(acceptInvitationController),
);
organizationsRouter.post(
  "/invitations/:invitationId/reject",
  validateParams(invitationIdParamsSchema),
  asyncHandler(rejectInvitationController),
);
organizationsRouter.delete(
  "/invitations/:invitationId",
  requirePermission("organization.invitation.manage"),
  validateParams(invitationIdParamsSchema),
  asyncHandler(cancelInvitationController),
);

organizationsRouter.get("/teams/user", asyncHandler(listUserTeamsController));
organizationsRouter.post(
  "/teams/active",
  validateBody(setActiveTeamSchema),
  asyncHandler(setActiveTeamController),
);
organizationsRouter.patch(
  "/teams/:teamId",
  requirePermission("organization.team.manage"),
  validateParams(teamIdParamsSchema),
  validateBody(updateTeamSchema),
  asyncHandler(updateTeamController),
);
organizationsRouter.delete(
  "/teams/:teamId",
  requirePermission("organization.team.manage"),
  validateParams(teamIdParamsSchema),
  asyncHandler(removeTeamController),
);
organizationsRouter.get(
  "/teams/:teamId/members",
  requirePermission("organization.team.read"),
  validateParams(teamIdParamsSchema),
  asyncHandler(listTeamMembersController),
);
organizationsRouter.post(
  "/teams/:teamId/members",
  requirePermission("organization.team.manage"),
  validateParams(teamIdParamsSchema),
  validateBody(addTeamMemberSchema),
  asyncHandler(addTeamMemberController),
);
organizationsRouter.delete(
  "/teams/:teamId/members/:userId",
  requirePermission("organization.team.manage"),
  validateParams(teamMemberParamsSchema),
  asyncHandler(removeTeamMemberController),
);

organizationsRouter.get(
  "/:organizationId",
  requirePermission("organization.read"),
  validateParams(organizationIdParamsSchema),
  asyncHandler(getOrganizationController),
);
organizationsRouter.patch(
  "/:organizationId",
  requirePermission("organization.update"),
  validateBody(updateOrganizationSchema),
  validateParams(organizationIdParamsSchema),
  asyncHandler(updateOrganizationController),
);
organizationsRouter.delete(
  "/:organizationId",
  requireOrgRole("owner"),
  validateParams(organizationIdParamsSchema),
  asyncHandler(deleteOrganizationController),
);
organizationsRouter.get(
  "/:organizationId/members",
  requirePermission("organization.member.read"),
  validateParams(organizationIdParamsSchema),
  asyncHandler(listMembersController),
);
organizationsRouter.post(
  "/:organizationId/members",
  requirePermission("organization.member.manage"),
  validateParams(organizationIdParamsSchema),
  validateBody(addMemberSchema),
  asyncHandler(addMemberController),
);
organizationsRouter.patch(
  "/:organizationId/members/:memberId/role",
  requirePermission("organization.member.manage"),
  validateParams(organizationMemberParamsSchema),
  validateBody(updateMemberRoleSchema),
  asyncHandler(updateMemberRoleController),
);
organizationsRouter.delete(
  "/:organizationId/members/:memberId",
  requirePermission("organization.member.manage"),
  validateParams(organizationMemberParamsSchema),
  asyncHandler(removeMemberController),
);
organizationsRouter.post(
  "/:organizationId/invitations",
  requirePermission("organization.invitation.manage"),
  validateBody(inviteMemberSchema),
  validateParams(organizationIdParamsSchema),
  asyncHandler(inviteMemberController),
);
organizationsRouter.post(
  "/:organizationId/teams",
  requirePermission("organization.team.manage"),
  validateParams(organizationIdParamsSchema),
  validateBody(createTeamSchema),
  asyncHandler(createTeamController),
);
organizationsRouter.get(
  "/:organizationId/teams",
  requirePermission("organization.team.read"),
  validateParams(organizationIdParamsSchema),
  asyncHandler(listOrganizationTeamsController),
);
