import type { LucideIcon } from "lucide-react";
import {
  Activity,
  BarChart3,
  Bell,
  Building2,
  Camera,
  ClipboardList,
  CreditCard,
  FileSearch,
  Gauge,
  GitCompareArrows,
  LayoutDashboard,
  Mail,
  Receipt,
  ShoppingCart,
  Users,
  Workflow,
} from "lucide-react";

export type ModulePriority = "P1" | "P2" | "P3" | "P4";

export interface ModuleDefinition {
  key: string;
  title: string;
  subtitle: string;
  icon: LucideIcon;
  routePath: string;
  priority: ModulePriority;
  progress: number;
  group: "core" | "ops" | "procurement" | "field" | "admin";
}

export const moduleRegistry: ModuleDefinition[] = [
  {
    key: "dashboard",
    title: "Dashboard",
    subtitle: "Overview and system health.",
    icon: Gauge,
    routePath: "/app",
    priority: "P1",
    progress: 72,
    group: "core",
  },
  {
    key: "command-center",
    title: "Command Center",
    subtitle: "Operational overview across all projects.",
    icon: Activity,
    routePath: "/app/command-center",
    priority: "P1",
    progress: 100,
    group: "ops",
  },
  {
    key: "activity-feed",
    title: "Activity Feed",
    subtitle: "Filtered activity stream with pagination.",
    icon: Activity,
    routePath: "/app/activity-feed",
    priority: "P1",
    progress: 100,
    group: "ops",
  },
  {
    key: "audit-log",
    title: "Audit Log",
    subtitle: "Immutable audit events and traceability.",
    icon: ClipboardList,
    routePath: "/app/audit-log",
    priority: "P1",
    progress: 100,
    group: "ops",
  },
  {
    key: "notifications",
    title: "Notifications",
    subtitle: "Alerts and team notifications.",
    icon: Bell,
    routePath: "/app/notifications",
    priority: "P1",
    progress: 95,
    group: "ops",
  },
  {
    key: "projects",
    title: "Projects",
    subtitle: "Manage construction projects.",
    icon: Building2,
    routePath: "/app/projects",
    priority: "P1",
    progress: 100,
    group: "core",
  },
  {
    key: "members",
    title: "Team",
    subtitle: "Members and invitations.",
    icon: Users,
    routePath: "/app/members",
    priority: "P1",
    progress: 100,
    group: "core",
  },
  {
    key: "change-orders",
    title: "Change Orders",
    subtitle: "Scope changes and approvals.",
    icon: Workflow,
    routePath: "/app/change-orders",
    priority: "P2",
    progress: 100,
    group: "procurement",
  },
  {
    key: "invoices",
    title: "Invoices",
    subtitle: "Vendor invoice tracking.",
    icon: Receipt,
    routePath: "/app/invoices",
    priority: "P2",
    progress: 100,
    group: "procurement",
  },
  {
    key: "purchase-orders",
    title: "Purchase Orders",
    subtitle: "PO lifecycle management.",
    icon: ShoppingCart,
    routePath: "/app/purchase-orders",
    priority: "P2",
    progress: 100,
    group: "procurement",
  },
  {
    key: "rfqs",
    title: "RFQs",
    subtitle: "Source package quotes and due dates.",
    icon: FileSearch,
    routePath: "/app/rfqs",
    priority: "P2",
    progress: 100,
    group: "procurement",
  },
  {
    key: "receipts",
    title: "Receipts",
    subtitle: "Track receiving confirmations and amounts.",
    icon: ClipboardList,
    routePath: "/app/receipts",
    priority: "P2",
    progress: 100,
    group: "procurement",
  },
  {
    key: "match-runs",
    title: "Match Runs",
    subtitle: "3-way match invoice, PO, and receipt.",
    icon: GitCompareArrows,
    routePath: "/app/match-runs",
    priority: "P2",
    progress: 100,
    group: "procurement",
  },
  {
    key: "budgets",
    title: "Budgets",
    subtitle: "Cost codes, variance, and alerts.",
    icon: BarChart3,
    routePath: "/app/budgets",
    priority: "P2",
    progress: 100,
    group: "procurement",
  },
  {
    key: "site-snaps",
    title: "SiteSnap AI",
    subtitle: "Field photos and AI observations.",
    icon: Camera,
    routePath: "/app/site-snaps",
    priority: "P3",
    progress: 100,
    group: "field",
  },
  {
    key: "subconnect",
    title: "SubConnect Ops",
    subtitle: "Subcontractor onboarding and compliance operations.",
    icon: Users,
    routePath: "/app/subconnect",
    priority: "P2",
    progress: 100,
    group: "ops",
  },
  {
    key: "smartmail",
    title: "SmartMail",
    subtitle: "Connected inbox and threads.",
    icon: Mail,
    routePath: "/app/smartmail",
    priority: "P3",
    progress: 100,
    group: "field",
  },
  {
    key: "billing",
    title: "Billing",
    subtitle: "Payments and subscription.",
    icon: CreditCard,
    routePath: "/app/billing",
    priority: "P2",
    progress: 100,
    group: "admin",
  },
];

export const NAV_GROUPS: { key: ModuleDefinition["group"]; label: string }[] = [
  { key: "core", label: "Workspace" },
  { key: "ops", label: "Operations" },
  { key: "procurement", label: "Procurement" },
  { key: "field", label: "Field" },
  { key: "admin", label: "Admin" },
];

export const moduleMap = new Map(
  moduleRegistry.map((module) => [module.key, module]),
);
